tag_cleaner:
  disabled: true
  tag_name: needtime
  limit: 100
  period: 1m

duration_checker:
  period: 1m

storage:
  db: collectordb
  user: collector
  password_env: DB_PASSWORD
  host: localhost
  port: 5432
  sslmode: disable
