tag_cleaner:
  tag_name: needtime
  limit: 100
  period: 1m

duration_checker:
  period: 1m

storage:
  db: collectordb
  user: kraysent
  password_env: DB_PASSWORD
  host: c-c9qlr6969sqkt9j1du0f.rw.mdb.yandexcloud.net
  port: 6432
  sslmode: require
